### ISSUE TITLE
Breadcrumb margin-top

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/default#38]
In 4.1, the breadcrumb is loading with a really big margin-top and getting hidden under the page title.

<img width="1396" alt="Screenshot 2024-03-06 at 16 20 40" src="https://github.com/omeka-s-themes/default/assets/28012148/46c8360c-4067-4cf4-ab24-ff1299f5df9f">
<img width="963" alt="Screenshot 2024-03-06 at 16 20 56" src="https://github.com/omeka-s-themes/default/assets/28012148/c8bf3f1f-5477-4562-9ffc-b5beda740d60">

**Comment by kimisgold** [comment]
The clipping is due to a negative bottom margin style. It seems to have been there since the theme styles were first written, so I'm having trouble remembering the reasoning behind it. For the moment, I've set a more moderately sized top and bottom margin, and I'll check them against various page configurations.

**Comment by allanaaa** [comment]
Looks good to me!
